"""Add PredictionLog table

Revision ID: 0d2d67980bd8
Revises: cbed0b461295
Create Date: 2025-12-22 23:01:05.692888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d2d67980bd8"
down_revision: Union[str, Sequence[str], None] = "286c8af40e7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prediction_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("image_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("raw_response", sa.JSON(), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prediction_logs_image_id"),
        "prediction_logs",
        ["image_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_prediction_logs_user_id"), "prediction_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prediction_logs_user_id"), table_name="prediction_logs")
    op.drop_index(op.f("ix_prediction_logs_image_id"), table_name="prediction_logs")
    op.drop_table("prediction_logs")
    # ### end Alembic commands ###
