"""add foodname in MealItem

Revision ID: 286c8af40e7f
Revises: 96da12e0d383
Create Date: 2025-12-11 13:49:00.622699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "286c8af40e7f"
down_revision: Union[str, Sequence[str], None] = "96da12e0d383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meal_items",
        sa.Column("foodname", sa.String(), nullable=False, server_default="UNKNOWN"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meal_items", "foodname")
    # ### end Alembic commands ###
