"""Fix typo in meal_items: nutiritionsta -> nutritions

Revision ID: 96da12e0d383
Revises: 810a6959eee1
Create Date: 2025-12-11 13:14:42.467458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96da12e0d383'
down_revision: Union[str, Sequence[str], None] = '810a6959eee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_items', sa.Column('nutritions', sa.JSON(), nullable=True))
    op.drop_column('meal_items', 'nutiritionsta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_items', sa.Column('nutiritionsta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('meal_items', 'nutritions')
    # ### end Alembic commands ###
