"""add provider field and make password nullable for social login

Revision ID: ef6762d11f05
Revises: 0d2d67980bd8
Create Date: 2025-12-24 20:23:18.231746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6762d11f05'
down_revision: Union[str, Sequence[str], None] = '0d2d67980bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. provider 컬럼 추가 (일단 nullable=True로)
    op.add_column('users', sa.Column('provider', sa.String(length=50), nullable=True))

    # 2. 기존 유저들에게 'local' 기본값 설정
    op.execute("UPDATE users SET provider = 'local' WHERE provider IS NULL")

    # 3. nullable=False로 변경
    op.alter_column('users', 'provider', nullable=False)

    # 4. password nullable 변경
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
